services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    hostname: serve-pops-laptop
    restart: unless-stopped
    privileged: true
    ports:
      - "7070:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '--docker_only=true'

  alloy:
   image: grafana/alloy:latest
   container_name: alloy
   hostname: serve-pops-laptop
   restart: unless-stopped
   privileged: true
   ports:
     - 12345:12345
     - 4317:4317
     - 4318:4318
   volumes:
     - ./config/config.alloy:/etc/alloy/config.alloy
     - /var/run/docker.sock:/var/run/docker.sock:ro
   command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy